#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

spring:
  application:
    name: wall-demo-auth
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:9918/wall?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: root
    password: wall_password
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis:
  mapper-locations:
    - classpath:mapperxml/account/*.xml
    - classpath:mapperxml/auth/*.xml
    - classpath:mapperxml/identity/authentication/*.xml
wall:
  plugin:
    auth:
      component:
        type: casbin
        casbin:
          model-path: casbin/model.conf
  rules:
    organization:
      name-length: 20
      name-rules: NO_SPECIAL_CHARACTER,NO_SPACE,NO_CHINESE
    user:
      salt-length: 18
      name-length: 20
      name-rules: NO_SPECIAL_CHARACTER,NO_SPACE,NO_CHINESE
    ug:
      name-length: 20
      name-rules: NO_SPECIAL_CHARACTER,NO_SPACE,NO_CHINESE
    authentication:
      cross-origin: "{'allow-credentials': 'true', 'allowed-headers': '*', 'allowed-methods': '*', 'allowed-origins': '*', 'exposed-headers': '*', 'max-age': '3600'}"
      token-prefix: wall-token
  token:
    returnType: header
    cookie:
      domain: 127.0.0.1
      max-age: 3600
      path: /
      secure: false
      name: wall-token
      http-only: false

    type: jwt
    jwt:
      algorithm: HS256
      secret: great wall for great application
      expiration: 3600
    token:
      token-header-name: wall-token
  credential:
    type: password
    password:
      algorithm: PBKDF2WithHmacSHA256
      salt-length: 18
      iterations: 1024
      key-length: 256
server:
  port: 10151